fragment SiteSettingsParts on SiteSettings {
  __typename
  heroHeadline
  heroTagline
  heroCta
  aboutTitle
  aboutBody
  credentials {
    __typename
    stat
    label
  }
  servicesTitle
  hrConsultingDesc
  c2cDesc
  contactEmail
  contactLinkedin
}
